name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.21'
    
    - name: Update plugin.yaml version
      run: |
        VERSION=$(cat VERSION)
        sed -i "s/^version: .*/version: $VERSION/" plugin.yaml
        echo "Updated plugin.yaml to version: $VERSION"
        
    - name: Build for all platforms
      run: |
        echo "=== Build Environment ==="
        go version
        go env GOOS GOARCH
        echo "========================="
        make cross-build
    
    - name: Package binaries
      run: |
        mkdir -p dist
        ls -la bin/
        for binary in bin/helm-safe-*; do
          echo "Processing: $binary"
          if [[ "$binary" == *".exe" ]]; then
            # Windows binary
            platform=$(basename "$binary" .exe | sed 's/helm-safe-//')
            echo "Creating Windows archive: helm-safe-${platform}.tar.gz"
            tar czf "dist/helm-safe-${platform}.tar.gz" -C bin "$(basename "$binary")"
          else
            # Unix binary - create as 'helm-safe' inside archive for consistency
            platform=$(basename "$binary" | sed 's/helm-safe-//')
            echo "Creating Unix archive: helm-safe-${platform}.tar.gz"
            # Create a temporary directory for this specific binary
            mkdir -p "temp-${platform}"
            cp "$binary" "temp-${platform}/helm-safe"
            tar czf "dist/helm-safe-${platform}.tar.gz" -C "temp-${platform}" "helm-safe"
            rm -rf "temp-${platform}"
          fi
        done
        echo "Generated archives:"
        ls -la dist/
        echo "Verifying archive contents:"
        for archive in dist/*.tar.gz; do
          echo "--- Contents of $archive ---"
          tar -tzf "$archive"
        done
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
